### ISSUE TITLE
Debugging for custom languages broken

### ISSUE THREAD

**Issue by borgdylan** [Microsoft/vscode-mono-debug#10]
I was debugging my custom .NET language code using this extension (added the extension for the files in the MonoDebugSession white list). In the past this used to work but after updating to the latest insiders build this is no ;longer the case.

**Comment by weinand** [comment]
@borgdylan could you please be more specific: what exactly does not work for you? Setting breakpoints? Launching? On which platform? Which version of mono? Which version of VS Code?

**Comment by borgdylan** [comment]
To set breakpoints I had to hack the configuration file to include the language. What does not work is stopping on the breakpoints I set. I am on Linux using the latest insiders build of Code on the latest mono from github.

**Comment by borgdylan** [comment]
To be more clear I am using Code v.  0.10.12-insider. When I will be using the PC in question I will post the commit SHA of mono and the extension version as well.

**Comment by borgdylan** [comment]
Full version info:
Code: 0.10.12-insider
vscode-mono-debug: 0.10.18
mono: f6de55f55857e60684ca1b85445dfb80309b0d28

**Comment by weinand** [comment]
@borgdylan could you please provide reproducible steps for your problem? A test project on github would be ideal.

**Comment by borgdylan** [comment]
I am using custom compilers currently which does not make it easy to reproduce. I will try the mono command lien debugger client and see if the issue arises from the mono debugger library being out of date in the code extension.

**Comment by borgdylan** [comment]
The sdb dependency on the extension is extremely out of date. It uses the May 2015 variant while the latest commits are dated January 2016.

**Comment by borgdylan** [comment]
A similar bug was fixed in the mono debugger libraries: https://github.com/mono/debugger-libs/commit/607c1dae16527b13377344b1f2ad2a221848e9d7

**Comment by borgdylan** [comment]
Fixed by renaming monoDebug.exe to mono-debug.exe
