### ISSUE TITLE
Use the Mono debugger library instead of SDB to enable Windows support

### ISSUE THREAD

**Issue by mattzink** [Microsoft/vscode-mono-debug#12]
It would be extremely useful to remote debug Mono applications from Windows. SDB is just a CLI wrapper for the mono debugger libraries (https://github.com/mono/debugger-libs). While SDB requires a POSIX environment to execute, the libraries do not. Please change this extension to depend upon the debugger libraries to enable Windows support.

**Comment by TheSHEEEP** [comment]
Indeed, not being able to use Mono with debugging on Windows is kinda weird.

**Comment by weinand** [comment]
I'm accepting pull requests!

**Comment by t-h-e** [comment]
I don't think the extension relies on SDB in a way that it requires to execute SDB. Therefore it does not require a POSIX environment.

If you adapt Initialize (https://github.com/t-h-e/vscode-mono-debug/commit/24da939de7aeb3fc58e2763da2e62314c6684d53), you can already use this extension on Windows. Although I had cygwin installed to build everything.

The project does rely on some of the code from the SDB project as well as its dependencies to Mono.Cecil, NRefactory, Mono.Debugger.Soft, Mono.Debugging and Mono.Debugging.Soft. I moved the dependencies to packages.config and added some code from SDB.

I created a pull request for the changes: https://github.com/Microsoft/vscode-mono-debug/pull/15
