### ISSUE TITLE
Error when trying to debug (f# on mono on OS X)

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-mono-debug#2]
_From @mmc41 on November 20, 2015 18:38_

When I try to debug a small hello-world like fsharp 4.0 program like the attached, I get an error "error while processing request '{_request}' (exception: {_exception})" in Visual Code 0.10.1 on OS X 10.10.5 on mono 4.2.1. The associated launch.json file is as follows:
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "mono",
			"request": "launch",
			"program": "hello2.exe",
			"args": ["test","test2","bla"],
			"cwd": ".",
			"runtimeExecutable": null,
			"env": {}
		},
		{
			"name": "Attach",
			"type": "mono",
			"request": "attach",
			"address": "localhost",
			"port": 5858
		}
	]
}

[hello2.txt](https://github.com/Microsoft/vscode/files/40396/hello2.txt)

_Copied from original issue: Microsoft/vscode#370_

**Comment by weinand** [comment]
_From @Oipo on November 21, 2015 7:59_

Same for me, VSCode 0.10.1, linux, using mono C#.

**Comment by weinand** [comment]
_From @borgdylan on November 22, 2015 12:50_

I can repro using a custom .NET language on Linux x86 using v. 0.10.1 as well. This used to work for plain .NET console apps in past versions.

**Comment by weinand** [comment]
This is a duplicate of #1.

**Comment by amansingh36** [comment]
@weinand, I'm also getting the same error. How we can solve this?

**Comment by amansingh36** [comment]
@mbcrump, I'm getting the same error. How we can solve this?

**Comment by thibault1907** [comment]
Me too!

**Comment by weinand** [comment]
@thibault1907 most likely this is a problem with passing environment variables to mono-debug. Please remove the "env": {}  from your launch config and try again. This bug will be fixed in the December release.

**Comment by weinand** [comment]
@thibault1907 if this hypothesis is your problem, then you can get a newer pre-release of mono-debug. Please see the mist recent comment on issue #1
