### ISSUE TITLE
Linux isn't same as Debian/Ubuntu

### ISSUE THREAD

**Issue by theel0ja** [microsoft/vscode-mono-debug#30]
In [README.md#installing-mono](https://github.com/Microsoft/vscode-mono-debug/blob/master/README.md#installing-mono), "Linux" installation guides is using `apt-get`, while it's only Debian's and Ubuntu's package manager, not all Linux distros have apt.

**Comment by weinand** [comment]
Feel free to provide a pull request to fix this.
