### ISSUE TITLE
Not stopping at breakpoints in Mono 5

### ISSUE THREAD

**Issue by zunder** [Microsoft/vscode-mono-debug#31]
It looks like attached mono-debug is not stopping at breakpoints while using mono 5.0.0.100 - Stable release (10 May 2017).

**Comment by TOTBWF** [comment]
To any others facing this issue, the move from xbuild to msbuild in mono 5 changed the way you need to generate debug symbols. You need to specify debugtype to be full, either by using `msbuild /p:DebugType=full` or by adding 
```
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
  </PropertyGroup>
```
to your project files.
