### ISSUE TITLE
Same thing, but for Visual Studio?

### ISSUE THREAD

**Issue by AlexeiScherbakov** [Microsoft/vscode-mono-debug#32]
It will be great if _big_ Visual Studio support this feature. Today only Xamarin Studio have it as 'hidden' feaure which is activated by "MONODEVELOP_SDB_TEST" environment variable. (http://codinggorilla.domemtech.com/?p=1490)

**Comment by weinand** [comment]
This extension is for Visual Studio Code. So I cannot do much about Visual Studio...
