### ISSUE TITLE
Replace debuger-libs binaries by source code

### ISSUE THREAD

**Issue by VysotskiVadim** [microsoft/vscode-mono-debug#36]
It's few reasons to replace debugger-libs binaries by source code:

1. debugger-libs classes like SoftDebuggerSession always fail silently, i.e. it just won't work without any exception and logs, so it really hard to understand what is wrong without debugging source code of debuger-libs.
2. debugger-libs isn't well documented, it doesn't have some kind of tutorials, so I believe that reading source code is the best way to understand how it works.
3. Owner of Mono.Debugger.Soft, Mono.Debugging and Mono.Debugging.Soft packages is Jetbrains: the release process isn't documented at all (at least I hasn't found any info about it).

**Comment by weinand** [comment]
@VysotskiVadim why do you think that the owner of Mono.Debugger.Soft, Mono.Debugging and Mono.Debugging.Soft packages is Jetbrains?

**Comment by VysotskiVadim** [comment]
![nuget gallery mono debugger soft 1 0 20170212 42 2017-06-15 16-35-07](https://user-images.githubusercontent.com/6190346/27183843-c68f6562-51e8-11e7-8c67-f1f6b3f4694e.png)

**Comment by VysotskiVadim** [comment]
Please, see pull request https://github.com/Microsoft/vscode-mono-debug/pull/37

**Comment by borgdylan** [comment]
I had raised this issue in the past. The maintainers of the actual source code should have been consulted by Jetbrains before their code was packaged and published under an owner that is not them. Also, there is no indication of whether Jetbrains applied any patches on the vanilla source code.

**Comment by akoeplinger** [comment]
debugger-libs was replaced with sources from a git submodule with https://github.com/microsoft/vscode-mono-debug/pull/64.
