### ISSUE TITLE
'All Exceptions' and 'Uncaught Exceptions' options disappear (C# - Mac)

### ISSUE THREAD

**Issue by kghandi** [Microsoft/vscode-mono-debug#41]
Using VS Code and vscode-mono-debug on a macOS 10.12 for a C# project. When the project is started, the debug panel briefly lists 'All Exceptions' and 'Uncaught Exceptions' options. But these disappear moments later when the debugger attaches to the xsp process.

<img width="416" alt="screen shot 2017-11-07 at 11 29 41 am" src="https://user-images.githubusercontent.com/6336722/32504981-12069014-c3af-11e7-970a-06e5e18f26aa.png">

<img width="423" alt="screen shot 2017-11-07 at 11 28 39 am" src="https://user-images.githubusercontent.com/6336722/32504986-16e8078e-c3af-11e7-8b94-840f4ce393b7.png">

The scripts/configurations which we use for starting the debugger are attached:

[Debug scripts.zip](https://github.com/Microsoft/vscode-mono-debug/files/1450845/Debug.scripts.zip)

project/launch.js
project/startServer.sh
project/.vscode/launch.json

**Comment by weinand** [comment]
This works as designed: mono-debug has no exception filter options.
