### ISSUE TITLE
Debugging is broken

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-mono-debug#42]
_From @borgdylan on January 6, 2018 17:44_

- VSCode Version: 1.20 insiders
- OS Version: Ubuntu 17.10 + Linux 4.14.12

Steps to Reproduce:

1. Try to debug a project that used to debug beforehand
2. Notice that breakpoints set are only listed in the viewlets, the editor does not show red circles in the gutter
3. Notice that breakpoints no longer hit

Does this issue occur when all extensions are disabled?: cannot test as debugger is an extension

_Copied from original issue: Microsoft/vscode#41227_

**Comment by auchenberg** [comment]
_From @borgdylan on January 6, 2018 17:53_

This was tested using the vscode-mono-debug extension. Used to work on the holiday themed builds of code-insiders.

**Comment by weinand** [comment]
This problem is independent from the mono debugger: I can reproduce this with JavaScript debugging too. There seems to be an issue with decorations on linux.

**Comment by weinand** [comment]
Verified that the problem is fixed in the latest Insiders.
