### ISSUE TITLE
Debugging with MONO_ENV_OPTIONS

### ISSUE THREAD

**Issue by yuhr** [microsoft/vscode-mono-debug#52]
Hi, I want to debug an application which must be launched without `mono` CLI. Currently I'm doing it by `attach` i.e. launching the app with `MONO_ENV_OPTIONS` environment variable set to `--debug --debugger-agent=transport=dt_socket,server=y,address=127.0.0.1:55555` and attaching the debugger to it. This configuration works well but frustrates me when I stop debugging as the app needs manual quit after disconnecting.

Is it possible to launch such an app directly upon the debugger?

**Comment by akoeplinger** [comment]
This was recently implemented as part of #66.
