### ISSUE TITLE
How can I get mono debugging working macOS Catalina? 

### ISSUE THREAD

**Issue by brian-themaven** [microsoft/vscode-mono-debug#62]
I know macOS Catalina stopped supporting 32bit applications so will this extension still work?  When I try to debug mono nunit tests with this extension, the breakpoints are not working.

**Comment by akoeplinger** [comment]
I'm using the extension on macOS Catalina without issue, but you need to make sure the mono that gets invoked is the 64bit-one and not the 32bit. How are you running/debugging the nunit tests?

**Comment by brian-themaven** [comment]
Thanks for your reply!  Since we only build 32bit binaries, I can only remote debug into our docker container.

**Comment by akoeplinger** [comment]
Ok yeah I think in that case you're out of luck given that Catalina doesn't support 32bit processes.
