### ISSUE TITLE
args array passed as a single argument when launching a mono program

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-mono-debug#9]
_From @alfonsogarciacaro on February 9, 2016 20:22_

Hi there! I'm experiencing an issue when debugging mono with the new version (0.10.8). This my launch configuration:
```
		{
			"name": "Launch",
			"type": "mono",
			"request": "launch",
			"program": "path/to/program.exe",
			"args": ["--projFile", "../../temp/Test.fsx"]
		}
```
Before, VS Code would pass two arguments to the program, but now it passes a single one with both strings joined without spaces ("--projFile../../temp/Test.fsx").

Please tell me if you need more info and thanks for your hard work!

_Copied from original issue: Microsoft/vscode#2862_

**Comment by weinand** [comment]
@alfonsogarciacaro I can reproduce for 0.10.8. This is a problem with the new internal console. As a workaround, you can enable the `externalConsole` and the problem will no longer occur.

This will be fixed in the February release.

**Comment by alfonsogarciacaro** [comment]
Perfect, thanks a lot for the tip!
