### ISSUE TITLE
Can you attach to NUnit tests running VS Code C# DevKit?

### ISSUE THREAD

**Issue by DigitalFlow** [microsoft/vscode-mono-debug#96]
Hi there,

we installed this extension and want to test .net 4.6.2 (full framework) assemblies in VS Code (on Linux) using the C# DevKit extension.

Executing tests works using mono.

But when trying to debug our unit tests they never reach a break point, although our projects all have <DebugType>full</DebugType> configured.
The debugger always shows "No symbols have been loaded for this document.".

Adding a launch.json with value 

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Mono",
            "request": "attach",
            "type": "mono",
            "address": "localhost",
            "port": 55555
        }
    ]
}

did not change this behaviour.

Is it possible to get vscode-momo-debug play with C# Dev Kit?

Kind regards,
Florian

**Comment by DigitalFlow** [comment]
I at least came as far as downloading a nunit-console build that works for .net-4.6.2 in linux and running it like this:

`mono --debug --debugger-agent=transport=dt_socket,server=y,address=127.0.0.1:55555 ../NUnit.Console-3.16.0/bin/nunit3-console.exe bin/Debug/net462/SomeProject.Tests.dll`

The above command starts mono and seems to wait for a debugger to attach.

With the launch.json from the initial post I'm able to attach from the VS Code debugger view, but no break point will be hit, the console runner just runs the tests (which pass) and exit.

Of course I compiled everything in Debug mode.

**Comment by akoeplinger** [comment]
The commands look good to me, the only thing I could imagine is that you're not using portable PDB files. Mono can't read the Windows-only "full" PDB files so make sure your project has `<DebugType>Portable</DebugType>`.

**Comment by DigitalFlow** [comment]
Thanks @akoeplinger,

I changed the DebugType and found out that furthermore I was relying on "System.Web.Services", which is not available in .NET Core.

After removing it from my code, debugging works as well.
Closing this.

Kind regards
Florian
